### ISSUE TITLE
Not able to run the rt_subscribe

### ISSUE THREAD

**Issue by marcelcastrobr** [Danielhiversen/pyTibber#170]
Hi, 
   First thanks for sharing this code.
  I am not sure if it is an issue or something I am doing wrong here.
I am trying to use pyTibber to get the power consumption data in realtime.
However when I run the code "Example realtime data", the output is:

_(py39) ➜  tibber python tibber_pulse.py
<tibber.Tibber object at 0x7fcdaa462490>
home is: <tibber.TibberHome object at 0x7fcdaa3e22e0>
Unexpected error
Traceback (most recent call last):
  File "/Users/castrma/miniconda3/envs/py39/lib/python3.9/site-packages/graphql_subscription_manager/__init__.py", line 143, in running
    await self._process_msg(msg)
  File "/Users/castrma/miniconda3/envs/py39/lib/python3.9/site-packages/graphql_subscription_manager/__init__.py", line 302, in _process_msg
    await callback(data)
  File "/Users/castrma/miniconda3/envs/py39/lib/python3.9/site-packages/tibber/__init__.py", line 697, in callback_add_extra_data
    _time = parse(data["data"]["liveMeasurement"]["timestamp"]).astimezone(
KeyError: 'data'_

By the way I was able to run the other example and get info on Monthly consumption and cost.

Packages:
graphql-subscription-manager 0.4.3
asyncio                      3.4.3
aiohttp                      3.8.1
Python 3.9.7

**Comment by Danielhiversen** [comment]
There are missing some exception handling in the latest version of the library.
You could try version 0.21.3

**Comment by marcelcastrobr** [comment]
Yes. it worked. Thanks @Danielhiversen.

**Comment by Danielhiversen** [comment]
I reopen this, since it needs to be fixed in the latest version
