### ISSUE TITLE
pyTibber 0.24.0 does not work with Python 3.10.4

### ISSUE THREAD

**Issue by asgaut** [Danielhiversen/pyTibber#194]
I get the following messages when attempting to run the first sample in the README:
```text
C:\workpriv\balena-homeassistant\peakprice-control\control.py:23: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Arya Stark
Traceback (most recent call last):
  File "C:\workpriv\balena-homeassistant\peakprice-control\control.py", line 24, in <module>
    loop.run_until_complete(main())
  File "C:\Users\rv76\Miniconda3\envs\peakprice-control\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\workpriv\balena-homeassistant\peakprice-control\control.py", line 12, in main
    home = tibber_connection.get_homes()[0]
IndexError: list index out of range
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002C7FD176D40>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002C7FD15A920>, 121785.375)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002C7FD176DD0>
```

It works when I downgrade to Python 3.9.13.

**Comment by Danielhiversen** [comment]
What is peakprice-control ?
´IndexError: list index out of range´ does not sound like a python 3.10 issue.

**Comment by asgaut** [comment]
You are right, those messages results form use of the DEMO_TOKEN (get_homes() returns an empty list).
With python 3.10 you get this warning:
```
DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```
See info on the deprecation here: https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop

The example code should probably just be updated.
