### ISSUE TITLE
Error on bad connection makes HA stops pulling

### ISSUE THREAD

**Issue by klem-everywhere** [Danielhiversen/pyTibber#207]
Here's the error log.

```
2022-10-10 01:23:50.760 INFO (MainThread) [homeassistant.setup] Setting up tibber
2022-10-10 01:23:50.760 INFO (MainThread) [homeassistant.setup] Setup of domain tibber took 0.0 seconds
2022-10-10 01:24:02.169 ERROR (MainThread) [tibber] Timed out when connecting to Tibber <--- I always get this one even when it works
2022-10-10 01:24:02.174 WARNING (MainThread) [homeassistant.config_entries] Config entry 'klem' for tibber integration not ready yet; Retrying in background <--- I always get this one even when it works
2022-10-10 01:24:27.356 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tibber
2022-10-10 01:24:32.111 ERROR (MainThread) [homeassistant.components.sensor] tibber: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/tibber/sensor.py", line 373, in async_update
    res = self._tibber_home.current_price_data()
  File "/usr/local/lib/python3.10/site-packages/tibber/tibber_home.py", line 368, in current_price_data
    return round(self.price_total[key], 3), self.price_level[key], price_time
KeyError: '2022-10-09T23:00:00.000+02:00'
2022-10-10 01:24:37.361 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform tibber is taking over 10 seconds.
2022-10-10 01:24:39.120 ERROR (MainThread) [homeassistant.components.sensor] tibber: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/tibber/sensor.py", line 373, in async_update
    res = self._tibber_home.current_price_data()
  File "/usr/local/lib/python3.10/site-packages/tibber/tibber_home.py", line 368, in current_price_data
    return round(self.price_total[key], 3), self.price_level[key], price_time
KeyError: '2022-10-09T23:00:00.000+02:00'
2022-10-10 01:24:39.159 INFO (MainThread) [homeassistant.components.notify] Setting up notify.tibber
```

**Comment by klem-everywhere** [comment]
Ohh it looks like it's fixed by https://github.com/Danielhiversen/pyTibber/pull/204
Will re-open if it is not the case.
