### ISSUE TITLE
Prohibited connection! - Connection error

### ISSUE THREAD

**Issue by mtomzig** [Danielhiversen/pyTibber#236]
Hi There.

I'm quite new to python and therefore I don't understand what's going on.

I've used the subscription example from your package and replaced "tibber.const.DEMO_TOKEN" with my token from the tibber developer-website. I also added an "asyncio.run(run())" at the end of the code to run the method. Here is the result:

`Prohibited connection!
Connection error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/graphql_subscription_manager/__init__.py", line 104, in running
    msg = await asyncio.wait_for(self.websocket.recv(), timeout=30)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (unexpected error); then sent 1011 (unexpected error)`

Can you help me to get thing running?

Regards
Mark

**Comment by Danielhiversen** [comment]
Does it work with the demo token?

**Comment by piotrbulinski** [comment]
@Danielhiversen could this be the culprit: https://developer.tibber.com/docs/overview#breaking-websocket-change ?

**Comment by Danielhiversen** [comment]
I don't think so.

**Comment by Danielhiversen** [comment]
Please test latest version and with demo token
