### ISSUE TITLE
Invalid session not actually raising Exception

### ISSUE THREAD

**Issue by janolehuebner** [Danielhiversen/pyTibber#280]
When using the "Example realtime data" from the README - after running for 3-12h I get 
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tibber/realtime.py", line 157, in _watchdog
    await self._resubscribe_homes()

  File "/usr/local/lib/python3.10/site-packages/tibber/realtime.py", line 178, in _resubscribe_homes
    await asyncio.gather(*[home.rt_resubscribe() for home in self._homes])

  File "/usr/local/lib/python3.10/site-packages/tibber/home.py", line 473, in rt_resubscribe
    await asyncio.gather(

  File "/usr/local/lib/python3.10/site-packages/tibber/home.py", line 202, in update_info
    if data := await self._tibber_control.execute(UPDATE_INFO % self._home_id):

  File "/usr/local/lib/python3.10/site-packages/tibber/__init__.py", line 104, in execute
    resp = await self.websession.post(API_ENDPOINT, **post_args)

  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")

RuntimeError: Session is closed

Watchdog: Connection is down, 2023-09-05 19:25:57.546125

Error in watchdog connect, retrying in 73 seconds
`

in the log output. I would expect this to cause the program to exit but the exception only appears in the output, causing the program to continue running but not actually doing anything. I coudn't figure out how to properly catch that and exit as I have no knowledge of the underlying stuff.
Any idea how I can catch this when using the "Example realtime data"?

**Comment by Danielhiversen** [comment]
N0 support for that today
